application: smallstep09
version: 1
runtime: python
api_version: 1

handlers:
#- url: /.*
#  script: asklogin.py

- url: /client/smallstep09\.xap
  static_files: /client/smallstep09.xap
  upload: /client/smallstep09\.xap
  mime_type: application/x-silverlight-2
  
- url: /client
  static_dir: client
  
- url: /images
  static_dir: images
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  mime_type: image/x-icon
  
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  
- url: /testpage.html
  static_files: testpage.html
  upload: testpage\.html
  
- url: /svc/.*
  script: services.py