application: smallstep09
version: 1
runtime: python
api_version: 1

handlers:
#- url: /.*
#  script: asklogin.py
  
- url: /includes
  static_dir: includes
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  mime_type: image/x-icon
  
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  
- url: /.*
  script: main.py